name = "mdblog-hono"
account_id = "ACCOUNT_ID_PLACEHOLDER"
main = "./dist/index.js"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

# 開発環境
[env.staging]
name = "mdblog-hono-staging"
[[env.staging.hyperdrive]]
binding = "HYPERDRIVE"
id = "HYPERDRIVE_ID_PLACEHOLDER"

# 本番環境
[env.production]
name = "mdblog-hono"
routes = [
  { pattern = "ROUTES_PATTERN_PLACEHOLDER", zone_name = "ROUTES_ZONE_PLACEHOLDER" }
]
[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "HYPERDRIVE_ID_PLACEHOLDER"